version: '3.8'
services:

    backend:
        container_name: "backend"
        build: 
            dockerfile: docker/Dockerfile_backend
        image: backend_image
        command: /backend_startup.sh
#        command: tail -f
        volumes:
            - ./backend:/usr/src/app
        ports:
            - 3000:3000
        networks:
            - transcendence-network
        env_file:
            - .env
        depends_on:
              - database
        restart: always

    frontend:
        container_name: "frontend"
        build: 
            dockerfile: docker/Dockerfile_frontend
        image: frontend_image
        command: npm run serve
        volumes:
            - ./frontend:/usr/src/app
        ports:
            - 8080:5173
        networks:
            - transcendence-network
        env_file:
            - .env
        depends_on:
              - database
              - backend
        restart: always

    database:
        container_name: "database"
        build: 
            dockerfile: docker/Dockerfile_database
        image: database_image
        networks:
            - transcendence-network
        volumes:
            - database_volume:/var/lib/postgresql/data
        env_file:
            - .env
        restart: always

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        env_file:
            - .env
        ports:
            - 5050:80
        networks:
            - transcendence-network
        depends_on:
              - database
        restart: always

# Cannot use bind volume because we don't have permissions,
# postgres official image use the postgres user.
volumes:
    database_volume:

networks:
    transcendence-network:
