FROM node:current-alpine3.17

COPY backend/package*.json .

COPY docker/backend_startup.sh .

#RUN chmod +x backend_startup.sh

RUN npm install --only=development

WORKDIR /app

CMD npm run start:dev
