FROM node:current-alpine3.17

WORKDIR /usr/src/app

ENV PATH="${PATH}:/node_modules/.bin/"

COPY docker/frontend_startup.sh /

RUN chmod +x /frontend_startup.sh

RUN apk add curl

ENTRYPOINT ["/frontend_startup.sh"]

CMD npm run serve
